instances_by_exit_status:
    skipped (submitted (exit_cost)):
    - pydata__xarray-7229
    skipped (submitted):
    - pydata__xarray-6992
    - pylint-dev__pylint-4551
    - pydata__xarray-7233
    - pydata__xarray-6938
    - pydata__xarray-7393
    submitted:
    - pylint-dev__pylint-4604
    - pylint-dev__pylint-4661
    - pylint-dev__pylint-6903
    - pylint-dev__pylint-6528
    - pylint-dev__pylint-7277
    - pytest-dev__pytest-10051
    - pylint-dev__pylint-8898
    - pylint-dev__pylint-7080
    - pytest-dev__pytest-10081
    - pytest-dev__pytest-10356
    - pytest-dev__pytest-5262
    - pytest-dev__pytest-5809
    - pytest-dev__pytest-5631
    - pytest-dev__pytest-5787
    - pytest-dev__pytest-6202
    - pytest-dev__pytest-7205
    - pytest-dev__pytest-5840
    - pytest-dev__pytest-7324
    - pytest-dev__pytest-6197
    - pytest-dev__pytest-7521
    - pytest-dev__pytest-7432
    - pytest-dev__pytest-7236
    - pytest-dev__pytest-7571
    - pytest-dev__pytest-7982
    - pytest-dev__pytest-7490
    - pytest-dev__pytest-8399
    - scikit-learn__scikit-learn-10844
    - scikit-learn__scikit-learn-10297
    submitted (exit_cost):
    - pylint-dev__pylint-6386
    submitted (exit_error):
    - pylint-dev__pylint-4970
total_cost: 10.303757899999999
