instances_by_exit_status:
    Uncaught CalledProcessError:
    - pytest-dev__pytest-5631
    - pytest-dev__pytest-6197
    - pytest-dev__pytest-6202
    - pytest-dev__pytest-7205
    - pytest-dev__pytest-7236
    exit_error:
    - pylint-dev__pylint-4551
    - pydata__xarray-6992
    - pydata__xarray-7233
    - pydata__xarray-7229
    - pydata__xarray-7393
    - pydata__xarray-6938
    - pylint-dev__pylint-4970
    - pylint-dev__pylint-4604
    - pylint-dev__pylint-6903
    - pylint-dev__pylint-4661
    - pylint-dev__pylint-6386
    - pylint-dev__pylint-6528
    - pylint-dev__pylint-7080
    - pylint-dev__pylint-7277
    - pylint-dev__pylint-8898
    - pytest-dev__pytest-10051
    - pytest-dev__pytest-10356
    - pytest-dev__pytest-10081
    - pytest-dev__pytest-5262
    - pytest-dev__pytest-5787
    - pytest-dev__pytest-5840
    - pytest-dev__pytest-5809
total_cost: 0
