instances_by_exit_status:
    submitted:
    - astropy__astropy-13236
    - astropy__astropy-13977
    - astropy__astropy-13579
    - astropy__astropy-13398
    submitted (exit_error):
    - astropy__astropy-13453
total_cost: 3.8873175000000004
