instances_by_exit_status:
    exit_error:
    - astropy__astropy-14096
    - astropy__astropy-14309
    - astropy__astropy-13453
    - astropy__astropy-14182
    - astropy__astropy-13398
    skipped (submitted):
    - astropy__astropy-13033
    - astropy__astropy-13579
    - astropy__astropy-12907
    - astropy__astropy-13236
    - astropy__astropy-13977
total_cost: 0
