instances_by_exit_status:
    Uncaught UnicodeEncodeError:
    - psf__requests-1766
    - pydata__xarray-3993
    exit_format:
    - mwaskom__seaborn-3069
    - psf__requests-1724
    - matplotlib__matplotlib-26342
    - psf__requests-2317
    - pydata__xarray-4687
    - pydata__xarray-6721
    - pydata__xarray-6461
    submitted:
    - pydata__xarray-3151
    - psf__requests-2931
    submitted (exit_cost):
    - pydata__xarray-4075
    submitted (exit_error):
    - pallets__flask-5014
    - pydata__xarray-2905
    - psf__requests-6028
    - psf__requests-5414
    - pydata__xarray-3305
    - pydata__xarray-4094
    submitted (exit_format):
    - mwaskom__seaborn-3187
    - matplotlib__matplotlib-26291
    - psf__requests-1921
    - psf__requests-1142
    - matplotlib__matplotlib-26466
    - pydata__xarray-3095
    - pydata__xarray-3677
    - pydata__xarray-4356
    - pydata__xarray-4695
    - pydata__xarray-4629
    - pydata__xarray-6744
    - pydata__xarray-6599
    - pydata__xarray-4966
total_cost: 9.319482039999995
